create database [DESAFIO_DATABASE]



CREATE TABLE
    DESAFIO_DATABASE.DBO.ENDERECO(
        ID INT NOT NULL PRIMARY KEY,
        RUA VARCHAR(255) NOT NULL,
        NUMERO INT NOT NULL,
        COMPLEMENTO VARCHAR(255),
        BAIRRO VARCHAR(255) NOT NULL,
        CIDADE VARCHAR(255) NOT NULL,
        UF VARCHAR(255) NOT NULL,
        CEP VARCHAR(255) NOT NULL
    );

CREATE TABLE
    DESAFIO_DATABASE.DBO.EMPRESA(
        ID INT NOT NULL PRIMARY KEY,
        NOME VARCHAR(255) NOT NULL,
        CNPJ VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255) NOT NULL,
        TELEFONE VARCHAR(255) NOT NULL,
        ENDERECO_ID INT FOREIGN KEY REFERENCES ENDERECO(ID)
    );

CREATE TABLE
    DESAFIO_DATABASE.DBO.COLABORADOR(
        ID INT NOT NULL PRIMARY KEY,
        CPF VARCHAR(255) NOT NULL,
        NOME VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255) NOT NULL,
        TELEFONE VARCHAR(255) NOT NULL,
        ENDERECO_ID INT REFERENCES ENDERECO(ID),
        EMPRESA_ID INT REFERENCES EMPRESA (ID),
        CARGO VARCHAR(255) NOT NULL
    )